import QueryProvider from '@/react-query/QueryProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Poke Dex.',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/ic-main.png'
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
