import { ConfirmProvider } from '@/contexts/confirm.context';
import { FormModalProvider } from '@/contexts/formModal.context';
import { ToastProvider } from '@/contexts/toast.context';
import QueryProvider from '@/react-query/QueryProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './_components/Header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Poke Dex.',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/ic-main.png'
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ToastProvider>
            <ConfirmProvider>
              <FormModalProvider>
                <Header />
                {children}
              </FormModalProvider>
            </ConfirmProvider>
          </ToastProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
